system:
    ip: 127.0.0.1
    port: 8080
db:
    mode: mysql
    host: 127.0.0.1
    port: 3306
    user: root
    password: ********
    db_name: rbacAdmin

redis:
    addr: 127.0.0.1:6379
    password: 
    db: 3