system:
#[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
# - using env:   export GIN_MODE=release
# - using code:  gin.SetMode(gin.ReleaseMode)


    #mode: release   # mode 意思是显示不显示debug
    ip: 127.0.0.1
    port: 8090
db:
    mode: mysql
    host: 192.168.10.199
    port: 3306
    user: root
    password: Zdj_7819!
    db_name: rbacAdmin

redis:
    addr: 192.168.10.199:6379
    password: 
    db: 3

jwt:
    secret: "aB3kL9mN7xY2qR8sT1uV4wE6zC0pF5gH"
    expires: 8
    issuer: "rbacAdmin"
   