system:
    ip: 127.0.0.1
    port: 8080
db:
    mode: mysql
    host: 192.168.10.199
    port: 3306
    user: root
    password: Zdj_7819!
    db_name: rbacAdmin

redis:
    addr: 192.168.10.199:6379
    password: 
    db: 3